/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        // Role stacks — Number digits face first (unicode-range), then role font.
        sans: [
          "var(--font-number-digits)",
          "var(--font-body)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        heading: [
          "var(--font-number-digits)",
          "var(--font-title)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        display: [
          "var(--font-number-digits)",
          "var(--font-title)",
          "Georgia",
          "Times New Roman",
          "serif",
        ],
        title: [
          "var(--font-number-digits)",
          "var(--font-title)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        body: [
          "var(--font-number-digits)",
          "var(--font-body)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        number: [
          "var(--font-number-digits)",
          "var(--font-number)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        cta: [
          "var(--font-number-digits)",
          "var(--font-cta)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        "main-menu": [
          "var(--font-number-digits)",
          "var(--font-main-menu)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        "sub-menu": [
          "var(--font-number-digits)",
          "var(--font-sub-menu)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        numeric: [
          "var(--font-numeric)",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "monospace",
        ],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        brand: {
          yellow: "hsl(var(--brand-yellow))",
          blue: "hsl(var(--brand-sky))",
          sky: "hsl(var(--brand-sky))",
          maroon: "hsl(var(--brand-maroon))",
          white: "hsl(var(--brand-white))",
          grey: "hsl(var(--brand-grey))",
          feather: "hsl(var(--brand-feather))",
          dusk: "hsl(var(--brand-dusk))",
          twilight: "hsl(var(--brand-twilight))",
          midnight: "hsl(var(--brand-midnight))",
          deep: "hsl(var(--brand-deep))",
          "green-rich": "hsl(var(--brand-green-rich))",
          "green-bright": "hsl(var(--brand-green-bright))",
          "green-tint": "hsl(var(--brand-green-tint))",
          "cherry-rich": "hsl(var(--brand-cherry-rich))",
          "cherry-bright": "hsl(var(--brand-cherry-bright))",
          "cherry-tint": "hsl(var(--brand-cherry-tint))",
          "berry-rich": "hsl(var(--brand-berry-rich))",
          "berry-bright": "hsl(var(--brand-berry-bright))",
          "berry-tint": "hsl(var(--brand-berry-tint))",
          "ocean-rich": "hsl(var(--brand-ocean-rich))",
          "ocean-bright": "hsl(var(--brand-ocean-bright))",
          "ocean-tint": "hsl(var(--brand-ocean-tint))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          active: "hsl(var(--primary-active))",
          subtle: "hsl(var(--primary-subtle))",
          border: "hsl(var(--primary-border))",
        },
        control: {
          DEFAULT: "hsl(var(--control))",
          foreground: "hsl(var(--control-foreground))",
          border: "hsl(var(--control-border))",
        },
        cta: {
          secondary: "hsl(var(--cta-secondary-fg))",
          tertiary: {
            DEFAULT: "hsl(var(--cta-tertiary-bg))",
            foreground: "hsl(var(--cta-tertiary-fg))",
            border: "hsl(var(--cta-tertiary-border))",
            hover: "hsl(var(--cta-tertiary-hover))",
          },
          ai: {
            DEFAULT: "hsl(var(--cta-ai-bg))",
            foreground: "hsl(var(--cta-ai-fg))",
            hover: "hsl(var(--cta-ai-hover))",
          },
          disabled: {
            DEFAULT: "hsl(var(--cta-disabled-bg))",
            foreground: "hsl(var(--cta-disabled-fg))",
          },
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          hover: "hsl(var(--secondary-hover))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        canvas: "hsl(var(--canvas))",
        "listing-header": {
          DEFAULT: "hsl(var(--listing-header-bg))",
          foreground: "hsl(var(--listing-header-fg))",
        },
        surface: {
          DEFAULT: "hsl(var(--surface))",
          border: "hsl(var(--surface-border))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        rail: {
          DEFAULT: "hsl(var(--rail))",
          foreground: "hsl(var(--rail-foreground))",
          active: "hsl(var(--rail-active))",
          "active-foreground": "hsl(var(--rail-active-foreground))",
        },
        panel: {
          DEFAULT: "hsl(var(--panel))",
          foreground: "hsl(var(--panel-foreground))",
          border: "hsl(var(--panel-border))",
        },
        // Semantic status tokens — used only by StatusBadge / VitalsIcon.
        status: {
          draft: { bg: "hsl(var(--status-draft-bg))", fg: "hsl(var(--status-draft-fg))" },
          qa: { bg: "hsl(var(--status-qa-bg))", fg: "hsl(var(--status-qa-fg))" },
          ready: { bg: "hsl(var(--status-ready-bg))", fg: "hsl(var(--status-ready-fg))" },
          running: { bg: "hsl(var(--status-running-bg))", fg: "hsl(var(--status-running-fg))" },
          analysis: { bg: "hsl(var(--status-analysis-bg))", fg: "hsl(var(--status-analysis-fg))" },
          paused: { bg: "hsl(var(--status-paused-bg))", fg: "hsl(var(--status-paused-fg))" },
          ended: { bg: "hsl(var(--status-ended-bg))", fg: "hsl(var(--status-ended-fg))" },
        },
        vitals: {
          healthy: "hsl(var(--vitals-healthy))",
          unhealthy: "hsl(var(--vitals-unhealthy))",
        },
        // Decision tokens — used only by DecisionIcon.
        decision: {
          "winner-fg": "hsl(var(--decision-winner-fg))",
          "baseline-fg": "hsl(var(--decision-baseline-fg))",
        },
        // Result tokens — used only for uplift values and the confidence bar.
        "success-fg": "hsl(var(--success-fg))",
        "danger-fg": "hsl(var(--danger-fg))",
        // Semantic families — tokens.json semantic.light (text / solid / subtleBg).
        "success-solid": "hsl(var(--success-solid))",
        "success-bg": "hsl(var(--success-bg))",
        "danger-bg": "hsl(var(--danger-bg))",
        "danger-on-subtle": "hsl(var(--danger-on-subtle))",
        "warning-fg": "hsl(var(--warning-fg))",
        "warning-solid": "hsl(var(--warning-solid))",
        "warning-bg": "hsl(var(--warning-bg))",
        "info-fg": "hsl(var(--info-fg))",
        "info-bg": "hsl(var(--info-bg))",
        "highlight-fg": "hsl(var(--highlight-fg))",
        "highlight-bg": "hsl(var(--highlight-bg))",
        // Selection + links — tokens.json primary.subtleBg / primary.default.
        "selected-bg": "hsl(var(--selected-bg))",
        "selected-fg": "hsl(var(--selected-fg))",
        link: {
          DEFAULT: "hsl(var(--link))",
          hover: "hsl(var(--link-hover))",
        },
        // Report tokens — used only by the campaign Reports page.
        report: {
          "green-deep": "hsl(var(--report-green-deep))",
          green: "hsl(var(--report-green))",
          "green-mid": "hsl(var(--report-green-mid))",
          "green-bar": "hsl(var(--report-green-bar))",
          "green-badge": "hsl(var(--report-green-badge))",
          "green-tint": "hsl(var(--report-green-tint))",
          "green-border": "hsl(var(--report-green-border))",
          red: "hsl(var(--report-red))",
          amber: "hsl(var(--report-amber))",
          track: "hsl(var(--report-track))",
          link: "hsl(var(--report-link))",
          "blue-bg": "hsl(var(--report-blue-bg))",
          "blue-border": "hsl(var(--report-blue-border))",
          "blue-fg": "hsl(var(--report-blue-fg))",
          "purple-bg": "hsl(var(--report-purple-bg))",
          "purple-border": "hsl(var(--report-purple-border))",
          "purple-fg": "hsl(var(--report-purple-fg))",
          "conclusion-bg": "hsl(var(--report-conclusion-bg))",
          brand: "hsl(var(--report-brand))",
          "brand-fg": "hsl(var(--report-brand-fg))",
          "brand-tint": "hsl(var(--report-brand-tint))",
          "ctrl-bg": "hsl(var(--report-ctrl-bg))",
          "ctrl-border": "hsl(var(--report-ctrl-border))",
          "ctrl-fg": "hsl(var(--report-ctrl-fg))",
          "v1-bg": "hsl(var(--report-v1-bg))",
          "v1-border": "hsl(var(--report-v1-border))",
          "v1-fg": "hsl(var(--report-v1-fg))",
          "v2-bg": "hsl(var(--report-v2-bg))",
          "v2-border": "hsl(var(--report-v2-border))",
          "v2-fg": "hsl(var(--report-v2-fg))",
          "prob-fill": "hsl(var(--report-prob-fill))",
          "info-bg": "hsl(var(--report-info-bg))",
          threshold: "hsl(var(--report-threshold))",
        },
        // Chart tokens — data-viz palette; mode-aware via --chart-* variables.
        // Series arrays for JS chart libs live in src/config/chartTokens.ts.
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
          6: "hsl(var(--chart-6))",
          7: "hsl(var(--chart-7))",
          8: "hsl(var(--chart-8))",
          9: "hsl(var(--chart-9))",
          10: "hsl(var(--chart-10))",
          11: "hsl(var(--chart-11))",
          12: "hsl(var(--chart-12))",
          13: "hsl(var(--chart-13))",
          14: "hsl(var(--chart-14))",
          15: "hsl(var(--chart-15))",
          16: "hsl(var(--chart-16))",
          17: "hsl(var(--chart-17))",
          18: "hsl(var(--chart-18))",
          19: "hsl(var(--chart-19))",
          20: "hsl(var(--chart-20))",
          positive: "hsl(var(--chart-positive))",
          "positive-bg": "hsl(var(--chart-positive-bg))",
          negative: "hsl(var(--chart-negative))",
          "negative-bg": "hsl(var(--chart-negative-bg))",
          warning: "hsl(var(--chart-warning))",
          "warning-bg": "hsl(var(--chart-warning-bg))",
          info: "hsl(var(--chart-info))",
          "info-bg": "hsl(var(--chart-info-bg))",
          baseline: "hsl(var(--chart-baseline))",
          "baseline-bg": "hsl(var(--chart-baseline-bg))",
          highlight: "hsl(var(--chart-highlight))",
          threshold: "hsl(var(--chart-threshold))",
          annotation: "hsl(var(--chart-annotation))",
          grid: "hsl(var(--chart-grid))",
          "grid-strong": "hsl(var(--chart-grid-strong))",
          "axis-line": "hsl(var(--chart-axis-line))",
          "axis-tick": "hsl(var(--chart-axis-tick))",
          label: "hsl(var(--chart-label))",
          "label-strong": "hsl(var(--chart-label-strong))",
          "tooltip-bg": "hsl(var(--chart-tooltip-bg))",
          "tooltip-text": "hsl(var(--chart-tooltip-text))",
          "tooltip-text-secondary": "hsl(var(--chart-tooltip-text-secondary))",
          "seq-1": "hsl(var(--chart-seq-1))",
          "seq-2": "hsl(var(--chart-seq-2))",
          "seq-3": "hsl(var(--chart-seq-3))",
          "seq-4": "hsl(var(--chart-seq-4))",
          "seq-5": "hsl(var(--chart-seq-5))",
          "seq-6": "hsl(var(--chart-seq-6))",
          "seq-7": "hsl(var(--chart-seq-7))",
          "div-1": "hsl(var(--chart-div-1))",
          "div-2": "hsl(var(--chart-div-2))",
          "div-3": "hsl(var(--chart-div-3))",
          "div-4": "hsl(var(--chart-div-4))",
          "div-5": "hsl(var(--chart-div-5))",
          "div-6": "hsl(var(--chart-div-6))",
          "div-7": "hsl(var(--chart-div-7))",
        },
        // shadcn destructive tokens — used only by shadcn/ui components.
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "var(--radius-xs)",
      },
      boxShadow: {
        "foundation-sm": "var(--shadow-sm)",
        "foundation-md": "var(--shadow-md)",
        "foundation-lg": "var(--shadow-lg)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.97)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 150ms ease-out",
        "fade-in-up": "fade-in-up 200ms ease-out",
        "scale-in": "scale-in 150ms ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
