/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        // Role stacks — Number digits face first (unicode-range), then role font.
        sans: [
          "var(--font-number-digits)",
          "var(--font-body)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        heading: [
          "var(--font-number-digits)",
          "var(--font-title)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        display: [
          "var(--font-number-digits)",
          "var(--font-title)",
          "Georgia",
          "Times New Roman",
          "serif",
        ],
        title: [
          "var(--font-number-digits)",
          "var(--font-title)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        body: [
          "var(--font-number-digits)",
          "var(--font-body)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        number: [
          "var(--font-number-digits)",
          "var(--font-number)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        cta: [
          "var(--font-number-digits)",
          "var(--font-cta)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        "main-menu": [
          "var(--font-number-digits)",
          "var(--font-main-menu)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        "sub-menu": [
          "var(--font-number-digits)",
          "var(--font-sub-menu)",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        numeric: [
          "var(--font-numeric)",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "monospace",
        ],
      },
      colors: {
        background: "rgb(from var(--background) r g b / <alpha-value>)",
        foreground: "rgb(from var(--foreground) r g b / <alpha-value>)",
        brand: {
          yellow: "rgb(from var(--brand-yellow) r g b / <alpha-value>)",
          blue: "rgb(from var(--brand-sky) r g b / <alpha-value>)",
          sky: "rgb(from var(--brand-sky) r g b / <alpha-value>)",
          maroon: "rgb(from var(--brand-maroon) r g b / <alpha-value>)",
          white: "rgb(from var(--brand-white) r g b / <alpha-value>)",
          grey: "rgb(from var(--brand-grey) r g b / <alpha-value>)",
          feather: "rgb(from var(--brand-feather) r g b / <alpha-value>)",
          dusk: "rgb(from var(--brand-dusk) r g b / <alpha-value>)",
          twilight: "rgb(from var(--brand-twilight) r g b / <alpha-value>)",
          midnight: "rgb(from var(--brand-midnight) r g b / <alpha-value>)",
          deep: "rgb(from var(--brand-deep) r g b / <alpha-value>)",
          "green-rich": "rgb(from var(--brand-green-rich) r g b / <alpha-value>)",
          "green-bright": "rgb(from var(--brand-green-bright) r g b / <alpha-value>)",
          "green-tint": "rgb(from var(--brand-green-tint) r g b / <alpha-value>)",
          "cherry-rich": "rgb(from var(--brand-cherry-rich) r g b / <alpha-value>)",
          "cherry-bright": "rgb(from var(--brand-cherry-bright) r g b / <alpha-value>)",
          "cherry-tint": "rgb(from var(--brand-cherry-tint) r g b / <alpha-value>)",
          "berry-rich": "rgb(from var(--brand-berry-rich) r g b / <alpha-value>)",
          "berry-bright": "rgb(from var(--brand-berry-bright) r g b / <alpha-value>)",
          "berry-tint": "rgb(from var(--brand-berry-tint) r g b / <alpha-value>)",
          "ocean-rich": "rgb(from var(--brand-ocean-rich) r g b / <alpha-value>)",
          "ocean-bright": "rgb(from var(--brand-ocean-bright) r g b / <alpha-value>)",
          "ocean-tint": "rgb(from var(--brand-ocean-tint) r g b / <alpha-value>)",
        },
        card: {
          DEFAULT: "rgb(from var(--card) r g b / <alpha-value>)",
          foreground: "rgb(from var(--card-foreground) r g b / <alpha-value>)",
        },
        popover: {
          DEFAULT: "rgb(from var(--popover) r g b / <alpha-value>)",
          foreground: "rgb(from var(--popover-foreground) r g b / <alpha-value>)",
        },
        primary: {
          DEFAULT: "rgb(from var(--primary) r g b / <alpha-value>)",
          foreground: "rgb(from var(--primary-foreground) r g b / <alpha-value>)",
          hover: "rgb(from var(--primary-hover) r g b / <alpha-value>)",
          active: "rgb(from var(--primary-active) r g b / <alpha-value>)",
          subtle: "rgb(from var(--primary-subtle) r g b / <alpha-value>)",
          border: "rgb(from var(--primary-border) r g b / <alpha-value>)",
        },
        control: {
          DEFAULT: "rgb(from var(--control) r g b / <alpha-value>)",
          foreground: "rgb(from var(--control-foreground) r g b / <alpha-value>)",
          border: "rgb(from var(--control-border) r g b / <alpha-value>)",
        },
        cta: {
          secondary: "rgb(from var(--cta-secondary-fg) r g b / <alpha-value>)",
          tertiary: {
            DEFAULT: "rgb(from var(--cta-tertiary-bg) r g b / <alpha-value>)",
            foreground: "rgb(from var(--cta-tertiary-fg) r g b / <alpha-value>)",
            border: "rgb(from var(--cta-tertiary-border) r g b / <alpha-value>)",
            hover: "rgb(from var(--cta-tertiary-hover) r g b / <alpha-value>)",
          },
          ai: {
            DEFAULT: "rgb(from var(--cta-ai-bg) r g b / <alpha-value>)",
            foreground: "rgb(from var(--cta-ai-fg) r g b / <alpha-value>)",
            hover: "rgb(from var(--cta-ai-hover) r g b / <alpha-value>)",
          },
          disabled: {
            DEFAULT: "rgb(from var(--cta-disabled-bg) r g b / <alpha-value>)",
            foreground: "rgb(from var(--cta-disabled-fg) r g b / <alpha-value>)",
          },
        },
        secondary: {
          DEFAULT: "rgb(from var(--secondary) r g b / <alpha-value>)",
          foreground: "rgb(from var(--secondary-foreground) r g b / <alpha-value>)",
          hover: "rgb(from var(--secondary-hover) r g b / <alpha-value>)",
        },
        muted: {
          DEFAULT: "rgb(from var(--muted) r g b / <alpha-value>)",
          foreground: "rgb(from var(--muted-foreground) r g b / <alpha-value>)",
        },
        canvas: "rgb(from var(--canvas) r g b / <alpha-value>)",
        "listing-header": {
          DEFAULT: "rgb(from var(--listing-header-bg) r g b / <alpha-value>)",
          foreground: "rgb(from var(--listing-header-fg) r g b / <alpha-value>)",
        },
        surface: {
          DEFAULT: "rgb(from var(--surface) r g b / <alpha-value>)",
          border: "rgb(from var(--surface-border) r g b / <alpha-value>)",
        },
        accent: {
          DEFAULT: "rgb(from var(--accent) r g b / <alpha-value>)",
          foreground: "rgb(from var(--accent-foreground) r g b / <alpha-value>)",
        },
        border: "rgb(from var(--border) r g b / <alpha-value>)",
        input: "rgb(from var(--input) r g b / <alpha-value>)",
        ring: "rgb(from var(--ring) r g b / <alpha-value>)",
        rail: {
          DEFAULT: "rgb(from var(--rail) r g b / <alpha-value>)",
          foreground: "rgb(from var(--rail-foreground) r g b / <alpha-value>)",
          active: "rgb(from var(--rail-active) r g b / <alpha-value>)",
          "active-foreground": "rgb(from var(--rail-active-foreground) r g b / <alpha-value>)",
        },
        panel: {
          DEFAULT: "rgb(from var(--panel) r g b / <alpha-value>)",
          foreground: "rgb(from var(--panel-foreground) r g b / <alpha-value>)",
          border: "rgb(from var(--panel-border) r g b / <alpha-value>)",
        },
        // Semantic status tokens — used only by StatusBadge / VitalsIcon.
        status: {
          draft: { bg: "rgb(from var(--status-draft-bg) r g b / <alpha-value>)", fg: "rgb(from var(--status-draft-fg) r g b / <alpha-value>)" },
          qa: { bg: "rgb(from var(--status-qa-bg) r g b / <alpha-value>)", fg: "rgb(from var(--status-qa-fg) r g b / <alpha-value>)" },
          ready: { bg: "rgb(from var(--status-ready-bg) r g b / <alpha-value>)", fg: "rgb(from var(--status-ready-fg) r g b / <alpha-value>)" },
          running: { bg: "rgb(from var(--status-running-bg) r g b / <alpha-value>)", fg: "rgb(from var(--status-running-fg) r g b / <alpha-value>)" },
          analysis: { bg: "rgb(from var(--status-analysis-bg) r g b / <alpha-value>)", fg: "rgb(from var(--status-analysis-fg) r g b / <alpha-value>)" },
          paused: { bg: "rgb(from var(--status-paused-bg) r g b / <alpha-value>)", fg: "rgb(from var(--status-paused-fg) r g b / <alpha-value>)" },
          ended: { bg: "rgb(from var(--status-ended-bg) r g b / <alpha-value>)", fg: "rgb(from var(--status-ended-fg) r g b / <alpha-value>)" },
        },
        vitals: {
          healthy: "rgb(from var(--vitals-healthy) r g b / <alpha-value>)",
          unhealthy: "rgb(from var(--vitals-unhealthy) r g b / <alpha-value>)",
        },
        // Decision tokens — used only by DecisionIcon.
        decision: {
          "winner-fg": "rgb(from var(--decision-winner-fg) r g b / <alpha-value>)",
          "baseline-fg": "rgb(from var(--decision-baseline-fg) r g b / <alpha-value>)",
        },
        // Result tokens — used only for uplift values and the confidence bar.
        "success-fg": "rgb(from var(--success-fg) r g b / <alpha-value>)",
        "danger-fg": "rgb(from var(--danger-fg) r g b / <alpha-value>)",
        // Semantic families — tokens.json semantic.light (text / solid / subtleBg).
        "success-solid": "rgb(from var(--success-solid) r g b / <alpha-value>)",
        "success-bg": "rgb(from var(--success-bg) r g b / <alpha-value>)",
        "danger-bg": "rgb(from var(--danger-bg) r g b / <alpha-value>)",
        "danger-on-subtle": "rgb(from var(--danger-on-subtle) r g b / <alpha-value>)",
        "warning-fg": "rgb(from var(--warning-fg) r g b / <alpha-value>)",
        "warning-solid": "rgb(from var(--warning-solid) r g b / <alpha-value>)",
        "warning-bg": "rgb(from var(--warning-bg) r g b / <alpha-value>)",
        "info-fg": "rgb(from var(--info-fg) r g b / <alpha-value>)",
        "info-bg": "rgb(from var(--info-bg) r g b / <alpha-value>)",
        "highlight-fg": "rgb(from var(--highlight-fg) r g b / <alpha-value>)",
        "highlight-bg": "rgb(from var(--highlight-bg) r g b / <alpha-value>)",
        // Selection + links — tokens.json primary.subtleBg / primary.default.
        "selected-bg": "rgb(from var(--selected-bg) r g b / <alpha-value>)",
        "selected-fg": "rgb(from var(--selected-fg) r g b / <alpha-value>)",
        link: {
          DEFAULT: "rgb(from var(--link) r g b / <alpha-value>)",
          hover: "rgb(from var(--link-hover) r g b / <alpha-value>)",
        },
        // Report tokens — used only by the campaign Reports page.
        report: {
          "green-deep": "rgb(from var(--report-green-deep) r g b / <alpha-value>)",
          green: "rgb(from var(--report-green) r g b / <alpha-value>)",
          "green-mid": "rgb(from var(--report-green-mid) r g b / <alpha-value>)",
          "green-bar": "rgb(from var(--report-green-bar) r g b / <alpha-value>)",
          "green-badge": "rgb(from var(--report-green-badge) r g b / <alpha-value>)",
          "green-tint": "rgb(from var(--report-green-tint) r g b / <alpha-value>)",
          "green-border": "rgb(from var(--report-green-border) r g b / <alpha-value>)",
          red: "rgb(from var(--report-red) r g b / <alpha-value>)",
          amber: "rgb(from var(--report-amber) r g b / <alpha-value>)",
          track: "rgb(from var(--report-track) r g b / <alpha-value>)",
          link: "rgb(from var(--report-link) r g b / <alpha-value>)",
          "blue-bg": "rgb(from var(--report-blue-bg) r g b / <alpha-value>)",
          "blue-border": "rgb(from var(--report-blue-border) r g b / <alpha-value>)",
          "blue-fg": "rgb(from var(--report-blue-fg) r g b / <alpha-value>)",
          "purple-bg": "rgb(from var(--report-purple-bg) r g b / <alpha-value>)",
          "purple-border": "rgb(from var(--report-purple-border) r g b / <alpha-value>)",
          "purple-fg": "rgb(from var(--report-purple-fg) r g b / <alpha-value>)",
          "conclusion-bg": "rgb(from var(--report-conclusion-bg) r g b / <alpha-value>)",
          brand: "rgb(from var(--report-brand) r g b / <alpha-value>)",
          "brand-fg": "rgb(from var(--report-brand-fg) r g b / <alpha-value>)",
          "brand-tint": "rgb(from var(--report-brand-tint) r g b / <alpha-value>)",
          "ctrl-bg": "rgb(from var(--report-ctrl-bg) r g b / <alpha-value>)",
          "ctrl-border": "rgb(from var(--report-ctrl-border) r g b / <alpha-value>)",
          "ctrl-fg": "rgb(from var(--report-ctrl-fg) r g b / <alpha-value>)",
          "v1-bg": "rgb(from var(--report-v1-bg) r g b / <alpha-value>)",
          "v1-border": "rgb(from var(--report-v1-border) r g b / <alpha-value>)",
          "v1-fg": "rgb(from var(--report-v1-fg) r g b / <alpha-value>)",
          "v2-bg": "rgb(from var(--report-v2-bg) r g b / <alpha-value>)",
          "v2-border": "rgb(from var(--report-v2-border) r g b / <alpha-value>)",
          "v2-fg": "rgb(from var(--report-v2-fg) r g b / <alpha-value>)",
          "prob-fill": "rgb(from var(--report-prob-fill) r g b / <alpha-value>)",
          "info-bg": "rgb(from var(--report-info-bg) r g b / <alpha-value>)",
          threshold: "rgb(from var(--report-threshold) r g b / <alpha-value>)",
        },
        // Chart tokens — data-viz palette; mode-aware via --chart-* variables.
        // Series arrays for JS chart libs live in src/config/chartTokens.ts.
        chart: {
          1: "rgb(from var(--chart-1) r g b / <alpha-value>)",
          2: "rgb(from var(--chart-2) r g b / <alpha-value>)",
          3: "rgb(from var(--chart-3) r g b / <alpha-value>)",
          4: "rgb(from var(--chart-4) r g b / <alpha-value>)",
          5: "rgb(from var(--chart-5) r g b / <alpha-value>)",
          6: "rgb(from var(--chart-6) r g b / <alpha-value>)",
          7: "rgb(from var(--chart-7) r g b / <alpha-value>)",
          8: "rgb(from var(--chart-8) r g b / <alpha-value>)",
          9: "rgb(from var(--chart-9) r g b / <alpha-value>)",
          10: "rgb(from var(--chart-10) r g b / <alpha-value>)",
          11: "rgb(from var(--chart-11) r g b / <alpha-value>)",
          12: "rgb(from var(--chart-12) r g b / <alpha-value>)",
          13: "rgb(from var(--chart-13) r g b / <alpha-value>)",
          14: "rgb(from var(--chart-14) r g b / <alpha-value>)",
          15: "rgb(from var(--chart-15) r g b / <alpha-value>)",
          16: "rgb(from var(--chart-16) r g b / <alpha-value>)",
          17: "rgb(from var(--chart-17) r g b / <alpha-value>)",
          18: "rgb(from var(--chart-18) r g b / <alpha-value>)",
          19: "rgb(from var(--chart-19) r g b / <alpha-value>)",
          20: "rgb(from var(--chart-20) r g b / <alpha-value>)",
          positive: "rgb(from var(--chart-positive) r g b / <alpha-value>)",
          "positive-bg": "rgb(from var(--chart-positive-bg) r g b / <alpha-value>)",
          negative: "rgb(from var(--chart-negative) r g b / <alpha-value>)",
          "negative-bg": "rgb(from var(--chart-negative-bg) r g b / <alpha-value>)",
          warning: "rgb(from var(--chart-warning) r g b / <alpha-value>)",
          "warning-bg": "rgb(from var(--chart-warning-bg) r g b / <alpha-value>)",
          info: "rgb(from var(--chart-info) r g b / <alpha-value>)",
          "info-bg": "rgb(from var(--chart-info-bg) r g b / <alpha-value>)",
          baseline: "rgb(from var(--chart-baseline) r g b / <alpha-value>)",
          "baseline-bg": "rgb(from var(--chart-baseline-bg) r g b / <alpha-value>)",
          highlight: "rgb(from var(--chart-highlight) r g b / <alpha-value>)",
          threshold: "rgb(from var(--chart-threshold) r g b / <alpha-value>)",
          annotation: "rgb(from var(--chart-annotation) r g b / <alpha-value>)",
          grid: "rgb(from var(--chart-grid) r g b / <alpha-value>)",
          "grid-strong": "rgb(from var(--chart-grid-strong) r g b / <alpha-value>)",
          "axis-line": "rgb(from var(--chart-axis-line) r g b / <alpha-value>)",
          "axis-tick": "rgb(from var(--chart-axis-tick) r g b / <alpha-value>)",
          label: "rgb(from var(--chart-label) r g b / <alpha-value>)",
          "label-strong": "rgb(from var(--chart-label-strong) r g b / <alpha-value>)",
          "tooltip-bg": "rgb(from var(--chart-tooltip-bg) r g b / <alpha-value>)",
          "tooltip-text": "rgb(from var(--chart-tooltip-text) r g b / <alpha-value>)",
          "tooltip-text-secondary": "rgb(from var(--chart-tooltip-text-secondary) r g b / <alpha-value>)",
          "seq-1": "rgb(from var(--chart-seq-1) r g b / <alpha-value>)",
          "seq-2": "rgb(from var(--chart-seq-2) r g b / <alpha-value>)",
          "seq-3": "rgb(from var(--chart-seq-3) r g b / <alpha-value>)",
          "seq-4": "rgb(from var(--chart-seq-4) r g b / <alpha-value>)",
          "seq-5": "rgb(from var(--chart-seq-5) r g b / <alpha-value>)",
          "seq-6": "rgb(from var(--chart-seq-6) r g b / <alpha-value>)",
          "seq-7": "rgb(from var(--chart-seq-7) r g b / <alpha-value>)",
          "div-1": "rgb(from var(--chart-div-1) r g b / <alpha-value>)",
          "div-2": "rgb(from var(--chart-div-2) r g b / <alpha-value>)",
          "div-3": "rgb(from var(--chart-div-3) r g b / <alpha-value>)",
          "div-4": "rgb(from var(--chart-div-4) r g b / <alpha-value>)",
          "div-5": "rgb(from var(--chart-div-5) r g b / <alpha-value>)",
          "div-6": "rgb(from var(--chart-div-6) r g b / <alpha-value>)",
          "div-7": "rgb(from var(--chart-div-7) r g b / <alpha-value>)",
        },
        // shadcn destructive tokens — used only by shadcn/ui components.
        destructive: {
          DEFAULT: "rgb(from var(--destructive) r g b / <alpha-value>)",
          foreground: "rgb(from var(--destructive-foreground) r g b / <alpha-value>)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "var(--radius-xs)",
      },
      boxShadow: {
        "foundation-sm": "var(--shadow-sm)",
        "foundation-md": "var(--shadow-md)",
        "foundation-lg": "var(--shadow-lg)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.97)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 150ms ease-out",
        "fade-in-up": "fade-in-up 200ms ease-out",
        "scale-in": "scale-in 150ms ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
